name: bump

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: self-hosted
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  default_bump: patch # major *.0.0 minor 0.*.0 patch 0.0.*

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.tag_version.outputs.new_tag }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to registry.timefactory.io
              uses: docker/login-action@v3
              with:
                registry: registry.timefactory.io
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                  registry.timefactory.io/factory:latest
                  registry.timefactory.io/factory:${{ steps.tag_version.outputs.new_tag }}